#lang planet neil/sicp
(define (filter predicate sequence)
  (cond ((null? sequence) nil)
        ((predicate (car sequence)) (cons (car sequence)
                                          (filter predicate (cdr sequence))))
        (else (filter predicate (cdr sequence)))))
(define (accumulate op initial sequence)
  (if (null? sequence)
      initial
      (op (car sequence)
          (accumulate op initial (cdr sequence)))))
(define (enumerate-interval low high)
  (if (> low high)
      nil
      (cons low (enumerate-interval (+ low 1) high))))
(define (flatmap proc seq)
  (accumulate append nil (map proc seq)))
(define (unique-pairs n)
  (flatmap (lambda (i)
             (map (lambda (j) (list i j))
                  (enumerate-interval 1 (- i 1))))
           (enumerate-interval 1 n)))

(define (unique-triples n)
  (flatmap (lambda (i)
              (map (lambda (j) (cons i j))
                   (unique-pairs (- i 1))))
           (enumerate-interval 1 n)))
;(unique-triples 4)

(define (ok? a-pair sum)
  (= (+ (car a-pair) (cadr a-pair)  (caddr a-pair))
     sum))
;(ok? (list 1 2 3) 6)

(define (s-sum-triples n s)
  (filter (lambda (x) (ok? x s))
          (unique-triples n)))
(s-sum-triples 5 12)
